name: public_testing_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.1
  get: ^4.6.6
  shared_preferences: ^2.2.2
  lottie: ^3.1.0
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  firebase_messaging: ^14.7.20
  firebase_auth: ^4.17.9
  introduction_screen: ^3.1.14
  sqflite: ^2.3.2
  pinput: ^4.0.0
  awesome_dialog: ^3.2.0
  iconsax: ^0.0.8
  file_picker: ^8.0.3
  image_picker: ^1.1.1
  path: ^1.9.0
  path_provider: ^2.1.3
  flutter_animate: ^4.5.0
  youtube_player_flutter: ^9.0.1
  mobkit_dashed_border: ^0.0.6
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.3
  connectivity_plus: ^6.0.3
  flutter_slidable: ^3.1.0
  marquee_text: ^2.5.0+1
  list_wheel_scroll_view_nls: ^0.0.3
  clickable_list_wheel_view: ^0.2.0
  flutter_downloader: ^1.11.7
  flutter_file_downloader: ^2.0.0
  easy_image_viewer: ^1.5.1
  flutter_file_view: ^2.2.1
  syncfusion_flutter_pdfviewer: ^26.1.41
  intl: ^0.19.0
  uuid: ^4.4.2
  scroll_snap_list: ^0.9.1
  awesome_notifications: ^0.9.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/images/online-learning.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/online-learning.png
  color_dark: "#555555"
  image_dark: assets/images/online-learning.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - .env
  fonts:
    - family: ProtestStrike
      fonts:
        - asset: assets/fonts/ProtestStrike-Regular.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-VariableFont_wght.ttf
    - family: InstrumentSerif
      fonts:
        - asset: assets/fonts/InstrumentSerif-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
    - family: PoetsenOne
      fonts:
        - asset: assets/fonts/PoetsenOne-Regular.ttf
